// ═══════════════════════════════════════════════════════════════════════
// Infinite OS — Desktop Environment + In-Browser AI Engine
// ═══════════════════════════════════════════════════════════════════════

// ─── AI Config ─────────────────────────────────────────────────────
// Uses remote API (g4f.space/pollinations) — no local model, no freeze.
const AI_API = "https://g4f.space/api/ollama/chat/completions";
let aiReady = false;
let aiChecked = false;
const appCache = {}; // Stores generated HTML by app id

// ─── OS App Spec (fed to the AI so it knows how to build apps) ─────
const APP_SPEC = `INFINITE OS - App Specification v1.0
Generate a SELF-CONTAINED HTML app. Rules:
1. Start with <div class="app-{name}">
2. CSS inside <style>, JS inside <script> — all inline
3. No external resources (no CDN, images, fonts)
4. Keep CSS SHORT — dark bg, white text, minimal styling
5. Make the app ACTUALLY WORK — the JS must be functional
6. Use global os object: os.notify(title,msg), os.fs.read/write(key,val)
7. The app MUST resize properly — use max-width, flex, grid, or viewport units
8. Scope CSS to the app class. Avoid global selectors like body, html, *, button, input
IMPORTANT: Output ONLY the HTML. No explanations. Keep code CONCISE.`;

function templateReference(desc) {
  if (typeof genTemplate !== "function") return "";
  const html = genTemplate(desc);
  const isGeneric =
    html.includes("📱") && html.includes("generated by the built-in template");
  if (isGeneric) return "";

  const visualReference = html
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/\s+on[a-z]+="[^"]*"/gi, "")
    .trim();

  return `

Built-in template reference for this kind of app, for visual/layout inspiration only.
Do not copy this exactly. Do not call TemplateApps. Write your own self-contained JavaScript.
Reference HTML/CSS:
${visualReference}`;
}

function buildPrompt(desc) {
  return `${APP_SPEC}${templateReference(desc)}

User request: "${desc}"

Generate the complete HTML for this app. Only output the HTML code, no other text.`;
}

function htmlEscape(value) {
  return String(value ?? "").replace(/[&<>"']/g, (ch) => {
    return {
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': "&quot;",
      "'": "&#39;",
    }[ch];
  });
}

function generationErrorHTML(desc) {
  return `<div class="app-generation-error">
<style>
.app-generation-error{padding:24px;font-family:system-ui,sans-serif;text-align:center;color:#e8e8f0}
.app-generation-error .ic{font-size:48px;margin-bottom:12px}
.app-generation-error h2{font-size:18px;margin:0 0 8px}
.app-generation-error p{margin:0;color:#9898b0;font-size:13px;line-height:1.5}
</style>
<div class="ic">⚠️</div>
<h2>Could not generate ${htmlEscape(desc)}</h2>
<p>The AI service did not return a usable app. Try again in a moment.</p>
</div>`;
}

// ─── Suggestions ────────────────────────────────────────────────────
const SUGGESTIONS = [
  ["🧮", "Calculator"],
  ["✅", "Todo List"],
  ["📝", "Notes"],
  ["🎨", "Paint"],
  ["🕐", "Clock"],
  ["🌤️", "Weather"],
  ["💬", "Chat"],
  ["🎵", "Music Player"],
  ["⏱️", "Stopwatch"],
  ["❌", "Tic Tac Toe"],
  ["📏", "Unit Converter"],
];

// ─── State ─────────────────────────────────────────────────────────
const S = { windows: {}, order: [], z: 100, launcher: false };

// ═══════════════════════════════════════════════════════════════════════
// HTML EXTRACTION (balanced div counting for AI output)
// ═══════════════════════════════════════════════════════════════════════

function extractHTML(text) {
  const m = text.match(/<div\s+class="app-[^"]*"/);
  if (!m) return null;
  let i = m.index,
    depth = 0,
    sc = false,
    st = false;
  while (i < text.length) {
    if (text.slice(i, i + 8) === "<script>") sc = true;
    if (text.slice(i, i + 9) === "</script>") {
      sc = false;
      i += 9;
      continue;
    }
    if (text.slice(i, i + 7) === "<style>") st = true;
    if (text.slice(i, i + 8) === "</style>") {
      st = false;
      i += 8;
      continue;
    }
    if (!sc && !st) {
      // Only count <div> tags for depth, not every tag
      if (text.slice(i, i + 4) === "<div" && text[i + 1] !== "/") {
        // Check it's not self-closing
        const close = text.indexOf(">", i);
        if (close > i && text[close - 1] !== "/") depth++;
      }
      if (text.slice(i, i + 6) === "</div>") {
        depth--;
        if (depth === 0) return text.slice(m.index, i + 6);
      }
    }
    i++;
  }
  // If we found the opening tag but couldn't find the closing one
  // (truncated output), return everything from the match onward.
  if (m) return text.slice(m.index);
  return null;
}

// ═══════════════════════════════════════════════════════════════════════
// AI ENGINE — Remote API (g4f.space/pollinations)
// ═══════════════════════════════════════════════════════════════════════

function bootMsg(msg, pct) {
  document.getElementById("boot-status").textContent = msg;
  if (pct !== undefined) {
    document.getElementById("boot-bar").style.width = Math.min(pct, 100) + "%";
  }
}

function dismissBoot() {
  const b = document.getElementById("boot");
  b.classList.add("hide");
  setTimeout(() => {
    if (b) b.style.display = "none";
  }, 700);
}

function initAI() {
  // Just dismiss the boot screen. First API call happens on user action.
  aiChecked = true;
  bootMsg("Ready", 100);
  setTimeout(dismissBoot, 300);
}

// ─── Streaming generation with live preview ───────────────────────────

async function streamApp(id, desc) {
  const prompt = buildPrompt(desc);

  const b = document.getElementById("wb-" + id);
  if (!b) return null;

  // Inject animation keyframes once
  if (!document.getElementById("gen-style")) {
    const s = document.createElement("style");
    s.id = "gen-style";
    s.textContent = `
      @keyframes blink{50%{opacity:0}}
      @keyframes pulseGlow{0%,100%{box-shadow:0 0 8px rgba(124,58,237,0)}50%{box-shadow:0 0 20px rgba(124,58,237,0.3)}}
      @keyframes dotPulse{0%,100%{opacity:0.3;transform:translateY(0)}50%{opacity:1;transform:translateY(-2px)}}
      .gen-dot{display:inline-block;width:6px;height:6px;border-radius:50%;background:#7c3aed;margin:0 2px;animation:dotPulse 1.2s ease-in-out infinite}
      .gen-dot:nth-child(2){animation-delay:0.2s}
      .gen-dot:nth-child(3){animation-delay:0.4s}
      .gen-status{transition:opacity 0.3s}
    `;
    document.head.appendChild(s);
  }

  // Terminal-like code preview with glow
  const winEl = document.getElementById("w-" + id);
  if (winEl) winEl.style.animation = "pulseGlow 2s ease-in-out infinite";

  b.style.background = "#0d1117";
  b.style.margin = "0";
  b.style.padding = "0";
  b.style.overflow = "auto";
  b.innerHTML = `<div style="padding:16px;font:13px/1.6 ui-monospace,monospace;color:#e6edf3">
  <div style="display:flex;align-items:center;gap:8px;margin-bottom:4px">
    <span style="color:#7c3aed">✦</span>
    <span style="color:#8b949e;font-size:11px">generating</span>
    <span class="gen-dot"></span><span class="gen-dot"></span><span class="gen-dot"></span>
    <span id="gen-stat-${id}" class="gen-status" style="margin-left:auto;font-size:11px;color:#58a6ff">connecting</span>
  </div>
  <div style="height:1px;background:linear-gradient(90deg,#7c3aed55,transparent);margin-bottom:12px"></div>
  <div style="display:flex;gap:0">
    <div style="color:#8b949e;text-align:right;padding-right:14px;user-select:none;opacity:0.5;min-width:32px" id="ln-${id}">1</div>
    <pre id="code-${id}" style="margin:0;font:inherit;color:#e6edf3;white-space:pre-wrap;word-break:break-all;flex:1"></pre>
  </div>
  <div style="margin-top:8px;display:flex;gap:10px;font-size:11px;color:#8b949e">
    <span id="gen-time-${id}">0.0s</span>
    <span id="gen-chars-${id}">0 chars</span>
  </div>
</div>`;

  try {
    const resp = await fetch(AI_API, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        messages: [{ role: "user", content: prompt }],
        model: "qwen3-coder-next",
        max_tokens: 4096,
        stream: true,
      }),
      signal: AbortSignal.timeout(60000),
    });

    if (!resp.ok) {
      const body = await resp.text().catch(() => "");
      console.log("[AI] API error:", resp.status, body.slice(0, 200));
      return null;
    }

    const reader = resp.body.getReader();
    const decoder = new TextDecoder();
    let fullText = "";
    let buffer = "";
    const codeEl = document.getElementById("code-" + id);

    const startTime = Date.now();
    const statusEl = document.getElementById("gen-stat-" + id);
    const timeEl = document.getElementById("gen-time-" + id);
    const charsEl = document.getElementById("gen-chars-" + id);
    const lnEl = document.getElementById("ln-" + id);

    // Cycle status messages based on what's being generated
    function updateStatus(text) {
      if (!statusEl) return;
      const t = text.toLowerCase();
      if (t.includes("<style")) statusEl.textContent = "styling";
      else if (t.includes("<script")) statusEl.textContent = "scripting";
      else if (t.includes("<div")) statusEl.textContent = "building";
      else if (t.includes("<html")) statusEl.textContent = "structuring";
      else if (t.includes("function")) statusEl.textContent = "coding";
      else if (t.includes("class")) statusEl.textContent = "composing";
      else if (t.includes("var ") || t.includes("let ") || t.includes("const "))
        statusEl.textContent = "initializing";
      else if (statusEl.textContent === "connecting" && text.length > 10)
        statusEl.textContent = "generating";
    }

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split("\n");
      buffer = lines.pop() || "";

      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed.startsWith("data: ")) continue;
        const data = trimmed.slice(6);
        if (data === "[DONE]") continue;
        try {
          const parsed = JSON.parse(data);
          const delta = parsed?.choices?.[0]?.delta?.content || "";
          if (delta) {
            fullText += delta;
            // Update display
            const safe = fullText
              .replace(/&/g, "&amp;")
              .replace(/</g, "&lt;")
              .replace(/>/g, "&gt;");
            if (codeEl) codeEl.textContent = safe;
            if (lnEl) lnEl.textContent = (safe.match(/\n/g) || []).length + 1;
            if (timeEl)
              timeEl.textContent =
                ((Date.now() - startTime) / 1000).toFixed(1) + "s";
            if (charsEl) charsEl.textContent = fullText.length + " chars";
            updateStatus(fullText);
            b.scrollTop = b.scrollHeight;
          }
        } catch (e) {}
      }
    }

    // First successful response marks AI as ready
    if (!aiReady) {
      aiReady = true;
      bootMsg("AI service connected", 100);
      setTimeout(dismissBoot, 400);
    }

    // Mark completion
    if (statusEl) statusEl.textContent = "done";
    if (winEl) winEl.style.animation = "";
    if (codeEl) codeEl.textContent += "\n\n✦ done";

    return fullText;
  } catch (e) {
    console.log("[AI] Streaming failed:", e.message);
    return null;
  }
}

async function genWithAI(desc) {
  // Non-streaming fallback
  const prompt = buildPrompt(desc);

  try {
    const resp = await fetch(AI_API, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        messages: [{ role: "user", content: prompt }],
        model: "qwen3-coder-next",
        max_tokens: 4096,
      }),
      signal: AbortSignal.timeout(60000),
    });

    if (!resp.ok) {
      const body = await resp.text().catch(() => "");
      console.log("[AI] API error:", resp.status, body.slice(0, 200));
      return null;
    }

    const data = await resp.json();
    const text = data?.choices?.[0]?.message?.content || "";
    console.log(`[AI] API returned ${text.length} chars`);

    if (!aiReady) {
      aiReady = true;
      bootMsg("AI service connected", 100);
      setTimeout(dismissBoot, 400);
    }

    return text;
  } catch (e) {
    console.log("[AI] Generation failed:", e.message);
    return null;
  }
}

// ═══════════════════════════════════════════════════════════════════════
// OS API (exposed to generated apps)
// ═══════════════════════════════════════════════════════════════════════

window.os = {
  window: {
    _id: null,
    get title() {
      const w = getWin(this._id);
      return w ? w.title : "";
    },
    set title(v) {
      const w = getWin(this._id);
      if (w) {
        w.title = v;
        updTitle(this._id);
      }
    },
    get icon() {
      const w = getWin(this._id);
      return w ? w.icon : "";
    },
    set icon(v) {
      const w = getWin(this._id);
      if (w) {
        w.icon = v;
        updTitle(this._id);
      }
    },
    get size() {
      const w = getWin(this._id);
      return w ? { w: w.w, h: w.h } : { w: 400, h: 300 };
    },
    resize(w, h) {
      resizeWin(this._id, w, h);
    },
  },
  fs: {
    read(k) {
      try {
        return localStorage.getItem("io_" + k);
      } catch (e) {
        return null;
      }
    },
    write(k, v) {
      try {
        localStorage.setItem("io_" + k, String(v));
        return true;
      } catch (e) {
        return false;
      }
    },
    list() {
      const a = [];
      for (let i = 0; i < localStorage.length; i++) {
        const k = localStorage.key(i);
        if (k && k.startsWith("io_"))
          a.push({ key: k.slice(3), size: localStorage.getItem(k).length });
      }
      return a;
    },
    delete(k) {
      try {
        localStorage.removeItem("io_" + k);
        return true;
      } catch (e) {
        return false;
      }
    },
  },
  notify(t, m) {
    showNotif(t, m);
  },
  get theme() {
    return "dark";
  },
  randomColor() {
    const c = [
      "#7c3aed",
      "#ef4444",
      "#f59e0b",
      "#10b981",
      "#3b82f6",
      "#ec4899",
      "#8b5cf6",
      "#14b8a6",
      "#f97316",
      "#06b6d4",
    ];
    return c[Math.floor(Math.random() * c.length)];
  },
  openApp(d) {
    openApp(d);
  },
};

// ═══════════════════════════════════════════════════════════════════════
// WINDOW MANAGER
// ═══════════════════════════════════════════════════════════════════════

function createWin(id, title, icon, w, h, x, y) {
  if (S.windows[id]) {
    focusWin(id);
    return S.windows[id];
  }
  const win = {
    id,
    title: title || "App",
    icon: icon || "📱",
    w: w || 520,
    h: h || 380,
    x: x || 80 + Math.random() * 120,
    y: y || 60 + Math.random() * 80,
    z: S.z++,
    max: false,
    min: false,
    prev: null,
  };
  S.windows[id] = win;
  S.order.push(id);
  renderWin(id);
  updTB();
  focusWin(id);
  return win;
}

function renderWin(id) {
  const w = S.windows[id];
  if (!w) return;
  const old = document.getElementById("w-" + id);
  if (old) old.remove();
  const el = document.createElement("div");
  el.className = "window" + (w.max ? " max" : "");
  el.id = "w-" + id;
  Object.assign(el.style, {
    left: w.x + "px",
    top: w.y + "px",
    width: w.w + "px",
    height: w.h + "px",
    zIndex: w.z,
  });
  el.dataset.id = id;
  el.innerHTML = `<div class="window-titlebar" onmousedown="dr(event,'${id}')"><div class="wc"><button class="wcc" onclick="cW('${id}')"></button><button class="wcm" onclick="mW('${id}')"></button><button class="wcx" onclick="MW('${id}')"></button></div><div class="t" id="wt-${id}"><span class="ie">${w.icon}</span>${w.title}</div><div class="wc" style="visibility:hidden"><button></button><button></button><button></button></div></div><div class="window-body" id="wb-${id}"></div><div class="wrz" onmousedown="rz(event,'${id}')"></div>`;
  document.getElementById("windows-container").appendChild(el);
  if (w.min) el.style.display = "none";
}

function getWin(id) {
  return S.windows[id] || null;
}
function updTitle(id) {
  const w = S.windows[id];
  if (!w) return;
  const e = document.getElementById("wt-" + id);
  if (e) e.innerHTML = `<span class="ie">${w.icon}</span>${w.title}`;
  updTB();
}

function focusWin(id) {
  const w = S.windows[id];
  if (!w) return;
  w.z = S.z++;
  const e = document.getElementById("w-" + id);
  if (e) e.style.zIndex = w.z;
  const i = S.order.indexOf(id);
  if (i > -1) S.order.splice(i, 1);
  S.order.push(id);
  updTB();
}

function cW(id) {
  const w = S.windows[id];
  if (!w) return;
  const e = document.getElementById("w-" + id);
  if (e) e.remove();
  delete S.windows[id];
  const i = S.order.indexOf(id);
  if (i > -1) S.order.splice(i, 1);
  updTB();
  if (S.order.length) focusWin(S.order[S.order.length - 1]);
}

function mW(id) {
  const w = S.windows[id];
  if (!w) return;
  w.min = !w.min;
  const e = document.getElementById("w-" + id);
  if (e) {
    e.style.display = w.min ? "none" : "";
    if (!w.min) focusWin(id);
  }
  updTB();
}

function MW(id) {
  const w = S.windows[id];
  if (!w) return;
  if (w.max) {
    w.max = false;
    if (w.prev) {
      w.x = w.prev.x;
      w.y = w.prev.y;
      w.w = w.prev.w;
      w.h = w.prev.h;
    }
  } else {
    w.prev = { x: w.x, y: w.y, w: w.w, h: w.h };
    w.max = true;
  }
  // Toggle maximize without destroying the DOM (preserves app content)
  const el = document.getElementById("w-" + id);
  if (el) {
    el.classList.toggle("max", w.max);
    if (!w.max) {
      el.style.left = w.x + "px";
      el.style.top = w.y + "px";
      el.style.width = w.w + "px";
      el.style.height = w.h + "px";
    }
  }
  updTB();
}

function resizeWin(id, w, h) {
  const win = S.windows[id];
  if (!win || win.max) return;
  win.w = Math.max(300, w);
  win.h = Math.max(200, h);
  const e = document.getElementById("w-" + id);
  if (e) {
    e.style.width = win.w + "px";
    e.style.height = win.h + "px";
  }
}

// ─── Window drag ─────────────────────────────────────────────────────
function dr(e, id) {
  if (e.target.closest(".wc")) return;
  const w = S.windows[id];
  if (!w || w.max) return;
  focusWin(id);
  const sx = e.clientX,
    sy = e.clientY,
    sl = w.x,
    st = w.y;
  const mv = (ev) => {
    w.x = sl + (ev.clientX - sx);
    w.y = st + (ev.clientY - sy);
    const el = document.getElementById("w-" + id);
    if (el) {
      el.style.left = w.x + "px";
      el.style.top = w.y + "px";
    }
  };
  const up = () => {
    document.removeEventListener("mousemove", mv);
    document.removeEventListener("mouseup", up);
  };
  document.addEventListener("mousemove", mv);
  document.addEventListener("mouseup", up);
}

function rz(e, id) {
  e.stopPropagation();
  const w = S.windows[id];
  if (!w || w.max) return;
  focusWin(id);
  const sx = e.clientX,
    sy = e.clientY,
    sw = w.w,
    sh = w.h;
  const mv = (ev) => {
    w.w = Math.max(300, sw + (ev.clientX - sx));
    w.h = Math.max(200, sh + (ev.clientY - sy));
    const el = document.getElementById("w-" + id);
    if (el) {
      el.style.width = w.w + "px";
      el.style.height = w.h + "px";
    }
  };
  const up = () => {
    document.removeEventListener("mousemove", mv);
    document.removeEventListener("mouseup", up);
  };
  document.addEventListener("mousemove", mv);
  document.addEventListener("mouseup", up);
}

// ═══════════════════════════════════════════════════════════════════════
// APP LAUNCHER
// ═══════════════════════════════════════════════════════════════════════

function appDocument(id, html) {
  const appId = JSON.stringify(id);
  return `<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<style>
:root{--bg:#0f0f1a;--bg2:#1a1a2e;--bg3:#252540;--surface:#ffffff08;--surface-hover:#ffffff14;--border:#ffffff14;--accent:#7c3aed;--accent-hover:#6d28d9;--text:#e8e8f0;--text2:#9898b0}
*,*::before,*::after{box-sizing:border-box}
html,body{margin:0;min-height:100%;background:transparent;color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",system-ui,sans-serif;color-scheme:dark}
body{overflow:auto}
button,input,textarea,select{font:inherit}
</style>
<script>
(() => {
  const appId = ${appId};
  const parentOs = parent.os;
  const withWindow = (fn) => {
    const previous = parentOs.window._id;
    parentOs.window._id = appId;
    try { return fn(); }
    finally { parentOs.window._id = previous; }
  };
  window.os = {
    fs: parentOs.fs,
    notify: (...args) => parentOs.notify(...args),
    get theme() { return parentOs.theme; },
    randomColor: () => parentOs.randomColor(),
    openApp: (desc) => parentOs.openApp(desc),
    window: {
      _id: appId,
      get title() { return withWindow(() => parentOs.window.title); },
      set title(value) { withWindow(() => { parentOs.window.title = value; }); },
      get icon() { return withWindow(() => parentOs.window.icon); },
      set icon(value) { withWindow(() => { parentOs.window.icon = value; }); },
      get size() { return withWindow(() => parentOs.window.size); },
      resize: (width, height) => withWindow(() => parentOs.window.resize(width, height)),
    },
  };
})();
</script>
</head>
<body>${html}</body>
</html>`;
}

function iconFor(n) {
  const l = n.toLowerCase();
  if (l.includes("calc") || l.includes("math")) return "🧮";
  if (l.includes("todo") || l.includes("task") || l.includes("list"))
    return "✅";
  if (l.includes("note") || l.includes("memo")) return "📝";
  if (l.includes("paint") || l.includes("draw") || l.includes("sketch"))
    return "🎨";
  if (l.includes("clock") || l.includes("time") || l.includes("watch"))
    return "🕐";
  if (l.includes("timer") || l.includes("stopwatch")) return "⏱️";
  if (l.includes("weather")) return "🌤️";
  if (l.includes("chat") || l.includes("ai") || l.includes("assistant"))
    return "💬";
  if (l.includes("music") || l.includes("player") || l.includes("sound"))
    return "🎵";
  if (l.includes("convert") || l.includes("unit")) return "📏";
  if (l.includes("tic") || l.includes("tac") || l.includes("toe")) return "❌";
  if (l.includes("color") || l.includes("picker")) return "🎨";
  return "📱";
}

function renderApp(id, desc, html) {
  const win = S.windows[id];
  if (!win) {
    createWin(id, desc, iconFor(desc), 540, 400);
  }
  const w = S.windows[id];
  if (!w) return;
  w.title = desc
    .split(" ")
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(" ");
  w.icon = iconFor(desc);
  updTitle(id);

  const b = document.getElementById("wb-" + id);
  if (!b) return;
  b.removeAttribute("style");
  b.innerHTML = "";

  if (html) {
    const frame = document.createElement("iframe");
    frame.className = "app-frame";
    frame.title = desc;
    frame.srcdoc = appDocument(id, html);
    b.appendChild(frame);
  }

  addDI(id, w.title, w.icon);
  updTB();
}

async function openApp(desc) {
  closeLauncher();
  const d = desc.trim();
  if (!d) return;
  const id =
    d
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_|_$/g, "") || "app";

  // If already open, just focus it
  if (S.windows[id]) {
    focusWin(id);
    return;
  }

  // If we have cached HTML, use it without regenerating
  if (appCache[id]) {
    renderApp(id, d, appCache[id]);
    return;
  }

  createWin(id, "Generating...", "⏳", 540, 400);
  const body = document.getElementById("wb-" + id);
  if (body) {
    body.style.display = "flex";
    body.style.alignItems = "center";
    body.style.justifyContent = "center";
    body.style.flexDirection = "column";
    body.innerHTML = `<div style="font-size:32px;animation:pulse 1s infinite">✦</div><div style="margin-top:12px;font-size:14px;color:var(--text2)">Creating "${d}"...</div><div style="margin-top:8px;font-size:12px;color:var(--text2);opacity:.5">This may take a moment</div>`;
  }

  // Templates are prompt references only; generated apps always come from AI.
  const raw = (await streamApp(id, d)) || (await genWithAI(d));
  const html = raw ? extractHTML(raw) : null;

  if (html) {
    appCache[id] = html;
    renderApp(id, d, html);
  } else {
    renderApp(id, d, generationErrorHTML(d));
  }
  updTB();

  if (!aiReady && !aiChecked) setTimeout(initAI, 500);
}

function addDI(id, name, emoji) {
  if (document.getElementById("di-" + id)) return;
  const el = document.createElement("div");
  el.className = "desktop-icon";
  el.id = "di-" + id;
  el.ondblclick = () => openApp(name);
  el.innerHTML = `<div class="icon-emoji">${emoji || "📱"}</div><div class="icon-label">${name}</div>`;
  document.getElementById("desktop-icons").appendChild(el);
}

// ═══════════════════════════════════════════════════════════════════════
// LAUNCHER
// ═══════════════════════════════════════════════════════════════════════

function toggleLauncher() {
  S.launcher ? closeLauncher() : openLauncher();
}

function openLauncher() {
  S.launcher = true;
  document.getElementById("launcher").classList.remove("hide");
  setTimeout(() => document.getElementById("launcher-inp").focus(), 50);
  document.getElementById("launcher-st").textContent = "";
  document.getElementById("launcher-sug").innerHTML = SUGGESTIONS.map(
    ([e, n]) =>
      `<div class="sug" onclick="openApp('${n.toLowerCase()}')">${e} ${n}</div>`,
  ).join("");
}

function closeLauncher() {
  S.launcher = false;
  document.getElementById("launcher").classList.add("hide");
}
function onLauncherKey(e) {
  if (e.key === "Enter") searchApp();
  else if (e.key === "Escape") closeLauncher();
}

async function searchApp() {
  const inp = document.getElementById("launcher-inp");
  const q = inp.value.trim();
  if (!q) return;
  document.getElementById("launcher-go").disabled = true;
  inp.disabled = true;
  document.getElementById("launcher-st").textContent = "✦ Generating...";
  await openApp(q);
  setTimeout(() => {
    inp.value = "";
    inp.disabled = false;
    document.getElementById("launcher-go").disabled = false;
    document.getElementById("launcher-st").textContent = "";
  }, 500);
}

// ═══════════════════════════════════════════════════════════════════════
// TASKBAR
// ═══════════════════════════════════════════════════════════════════════

function updTB() {
  const c = document.getElementById("tb-apps");
  c.innerHTML = "";
  S.order.forEach((id) => {
    const w = S.windows[id];
    if (!w) return;
    const btn = document.createElement("button");
    btn.className =
      "tb-app" + (id === S.order[S.order.length - 1] ? " on" : "");
    btn.innerHTML = `${w.icon} ${w.title}`;
    btn.onclick = () => {
      if (w.min) {
        w.min = false;
        const el = document.getElementById("w-" + id);
        if (el) el.style.display = "";
        focusWin(id);
      } else if (id === S.order[S.order.length - 1]) mW(id);
      else focusWin(id);
    };
    c.appendChild(btn);
  });
}

// ═══════════════════════════════════════════════════════════════════════
// NOTIFICATIONS
// ═══════════════════════════════════════════════════════════════════════

function showNotif(t, m) {
  const c = document.getElementById("notif-box");
  const el = document.createElement("div");
  el.className = "notif";
  el.onclick = () => el.remove();
  el.innerHTML = `<div class="nf-t">${t}</div><div class="nf-m">${m}</div>`;
  c.appendChild(el);
  setTimeout(() => {
    if (el.parentElement) el.remove();
  }, 5000);
}

// ═══════════════════════════════════════════════════════════════════════
// CLOCK / EVENTS / INIT
// ═══════════════════════════════════════════════════════════════════════

function clock() {
  document.getElementById("tb-clock").textContent =
    new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
}

// Context menu
document.addEventListener("contextmenu", (e) => {
  e.preventDefault();
  const m = document.getElementById("ctx");
  m.style.left = Math.min(e.clientX, window.innerWidth - 200) + "px";
  m.style.top = Math.min(e.clientY, window.innerHeight - 250) + "px";
  m.classList.remove("hide");
});
document.addEventListener("click", (e) => {
  if (!e.target.closest("#ctx"))
    document.getElementById("ctx").classList.add("hide");
});
document
  .getElementById("desktop")
  .addEventListener("click", () =>
    document.getElementById("ctx").classList.add("hide"),
  );

function showAbout() {
  document.getElementById("ctx").classList.add("hide");
  const o = document.createElement("div");
  o.className = "ab-o";
  o.onclick = (e) => {
    if (e.target === o) o.remove();
  };
  o.innerHTML = `<div class="ab-b"><h1>✦</h1><h2>Infinite OS</h2><p>A web operating system where every app is generated by AI on demand.</p><p style="font-size:12px;opacity:.4">AI: remote API (no local model needed)<br>No server, no login, no data leaves your machine<br>v1.0.0</p><button onclick="this.closest('.ab-o').remove()">Close</button></div>`;
  document.body.appendChild(o);
}

document.addEventListener("keydown", (e) => {
  if (e.key === "Escape" && S.launcher) closeLauncher();
  if ((e.ctrlKey || e.metaKey) && e.key === "k") {
    e.preventDefault();
    toggleLauncher();
  }
});

// ─── Boot ────────────────────────────────────────────────────────────
clock();
setInterval(clock, 1000);
console.log("✦ Infinite OS loaded");
setTimeout(initAI, 2000);
