// ═══════════════════════════════════════════════════════════════════════
// Infinite OS — Desktop Environment + Cloud AI Engine (Google Gemini)
// ═══════════════════════════════════════════════════════════════════════

// ─── Backend Configuration ─────────────────────────────────────────
const AI_BACKEND_URL = "https://gemini-proxy.niccata24.workers.dev/gemini";

const AI_MODEL = "gemini-2.0-flash";
const AI_TEMPERATURE = 0.9;
const AI_MAX_TOKENS = 65536;

const appCache = {};

// ─── OS App Spec (fed to the AI so it knows how to build apps) ─────
const APP_SPEC = `You are an expert HTML/CSS/JS developer. Build a polished, feature-rich, visually impressive HTML app that looks like a real desktop application.

First, think through the requirements inside <thinking> tags. Then output the complete HTML code.

---
REQUIREMENTS
---
- Start your app with <div class="app-{name}"> as the root container element.
- Everything must be self-contained inline: <style> for CSS, <script> for JS.
- Design a rich, polished dark UI. Use gradients, shadows, border-radius, smooth transitions, proper spacing, and visual hierarchy. Make it look like a high-quality native app, not a prototype.
- Full working JavaScript with all features, event handlers, keyboard shortcuts, error handling, and DOM updates.
- Scoped CSS: prefix all selectors with .app-{name} to avoid conflicts.
- You MAY use <iframe> to embed external content (maps, charts, videos, web widgets, music services like https://radio.garden/, etc.) — set allow="*" and sandbox as needed. This is great for rich data visualizations or embedded services.
- For games: render a proper UI with score, controls, restart button, and visual polish.
- Do NOT use external resources, CDN links, or external images. Everything must be inline.

---
CRITICAL: WINDOW RESIZE / RESPONSIVE LAYOUT
---
Your app lives inside an iframe that users can resize at any time by dragging the window edge or maximizing it. The iframe's width and height change dynamically.

You MUST make your app fill and adapt to the available space:
- Set the root <div class="app-{name}"> to width:100%; height:100% so it fills the iframe.
- Design all layouts with flexbox, grid, or percentage-based sizing — never use fixed pixel widths on the overall layout.
- For scrollable content, use overflow:auto on the appropriate container so content doesn't get clipped when the window shrinks.
- Optionally use a ResizeObserver on the root element to re-render or reflow canvas/grid/tile layouts when the window dimensions change.
- What NOT to do: do NOT set a fixed width/height on the outer container; do NOT assume the window is always the same size; do NOT center a small box in the middle of a huge space without filling the rest.

---
AVAILABLE OS APIs (use these to make your app feel native & persistent)
---
os.notify(title, message)       — Show a notification toast
os.fs.read(key)                 — Read saved data (returns string or null)
os.fs.write(key, value)         — Save/ persist data
os.fs.list()                    — List all saved files [{key, size}]
os.fs.delete(key)               — Delete saved data
os.openApp(description)         — Launch another app by name
theme = os.theme                — Current theme ("dark")
color = os.randomColor()        — Random accent color from the OS palette
os.window.title = "..."         — Change the window title
os.window.icon = "..."          — Change the window icon
os.window.resize(w, h)          — Resize the window

Build something impressive, fully functional, and beautifully styled.`;

function templateReference(desc) {
  if (typeof genTemplate !== "function") return "";
  const html = genTemplate(desc);
  const isGeneric =
    html.includes("📱") && html.includes("generated by the built-in template");
  if (isGeneric) return "";

  const visualReference = html
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/\s+on[a-z]+="[^"]*"/gi, "")
    .trim();

  return `

Built-in template reference for this kind of app, for visual/layout inspiration only.
Do not copy this exactly. Do not call TemplateApps. Write your own self-contained JavaScript.
Reference HTML/CSS:
${visualReference}`;
}

function buildPrompt(desc) {
  return `${APP_SPEC}${templateReference(desc)}

User request: "${desc}"

Generate the complete HTML for this app. Only output the HTML code, no other text.`;
}

function htmlEscape(value) {
  return String(value ?? "").replace(/[&<>"']/g, (ch) => {
    return {
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': "&quot;",
      "'": "&#39;",
    }[ch];
  });
}

function generationErrorHTML(desc) {
  return `<div class="app-generation-error">
<style>
.app-generation-error{padding:24px;font-family:system-ui,sans-serif;text-align:center;color:#e8e8f0}
.app-generation-error .ic{font-size:48px;margin-bottom:12px}
.app-generation-error h2{font-size:18px;margin:0 0 8px}
.app-generation-error p{margin:0;color:#9898b0;font-size:13px;line-height:1.5}
</style>
<div class="ic">⚠️</div>
<h2>Could not generate ${htmlEscape(desc)}</h2>
<p>The AI service did not return a usable app. Try again in a moment.</p>
</div>`;
}

// ─── State ─────────────────────────────────────────────────────────
const S = { windows: {}, order: [], z: 100, launcher: false };

// ═══════════════════════════════════════════════════════════════════════
// HTML EXTRACTION (balanced div counting for AI output)
// ═══════════════════════════════════════════════════════════════════════

function extractHTML(text) {
  const m = text.match(/<div\s+class="app-[^"]*"/);
  if (!m) return null;
  let i = m.index,
    depth = 0,
    sc = false,
    st = false;
  while (i < text.length) {
    if (text.slice(i, i + 8) === "<script>") sc = true;
    if (text.slice(i, i + 9) === "</script>") {
      sc = false;
      i += 9;
      continue;
    }
    if (text.slice(i, i + 7) === "<style>") st = true;
    if (text.slice(i, i + 8) === "</style>") {
      st = false;
      i += 8;
      continue;
    }
    if (!sc && !st) {
      if (text.slice(i, i + 4) === "<div" && text[i + 1] !== "/") {
        const close = text.indexOf(">", i);
        if (close > i && text[close - 1] !== "/") depth++;
      }
      if (text.slice(i, i + 6) === "</div>") {
        depth--;
        if (depth === 0) return text.slice(m.index, i + 6);
      }
    }
    i++;
  }
  if (m) return text.slice(m.index);
  return null;
}

function bootMsg(msg, pct) {
  const el = document.getElementById("boot-status");
  if (el) el.textContent = msg;
  if (pct !== undefined) {
    const bar = document.getElementById("boot-bar");
    if (bar) bar.style.width = Math.min(pct, 100) + "%";
  }
}

function createStars() {
  const container = document.getElementById("boot-stars");
  if (!container) return;
  for (let i = 0; i < 80; i++) {
    const star = document.createElement("div");
    const size = Math.random() * 2 + 1;
    star.style.cssText = `
      position:absolute;
      width:${size}px;height:${size}px;
      background:rgba(255,255,255,${Math.random() * 0.4 + 0.2});
      border-radius:50%;
      left:${Math.random() * 100}%;
      top:${Math.random() * 100}%;
      animation:twinkle ${Math.random() * 3 + 2}s ease-in-out infinite alternate;
      animation-delay:${Math.random() * 3}s;
    `;
    container.appendChild(star);
  }
}

function playStartupSound() {
  let played = false;
  const play = () => {
    if (played) return;
    played = true;
    try {
      const ctx = new (window.AudioContext || window.webkitAudioContext)();
      if (ctx.state === "suspended") ctx.resume();
      const now = ctx.currentTime;

      // Rising arpeggio: C5 → E5 → G5 → C6
      const notes = [523.25, 659.25, 783.99, 1046.5];
      notes.forEach((freq, i) => {
        const osc = ctx.createOscillator();
        const gain = ctx.createGain();
        osc.type = "sine";
        osc.frequency.setValueAtTime(freq, now + i * 0.1);
        gain.gain.setValueAtTime(0, now + i * 0.1);
        gain.gain.linearRampToValueAtTime(0.1, now + i * 0.1 + 0.04);
        gain.gain.exponentialRampToValueAtTime(0.001, now + i * 0.1 + 0.35);
        osc.connect(gain).connect(ctx.destination);
        osc.start(now + i * 0.1);
        osc.stop(now + i * 0.1 + 0.4);
      });

      // Soft sub-bass pad underneath
      const sub = ctx.createOscillator();
      const subGain = ctx.createGain();
      sub.type = "sine";
      sub.frequency.setValueAtTime(130.81, now);
      subGain.gain.setValueAtTime(0, now);
      subGain.gain.linearRampToValueAtTime(0.04, now + 0.1);
      subGain.gain.exponentialRampToValueAtTime(0.001, now + 0.8);
      sub.connect(subGain).connect(ctx.destination);
      sub.start(now);
      sub.stop(now + 1);
    } catch (_) {}
  };

  // Defer AudioContext creation to first user gesture (avoids autoplay warnings)
  document.addEventListener("pointerdown", play, { once: true });
  document.addEventListener("keydown", play, { once: true });
}

// ═══════════════════════════════════════════════════════════════════════
// GOOGLE GEMINI API
// ═══════════════════════════════════════════════════════════════════════

async function callAI(prompt, onStream) {
  const url = `${AI_BACKEND_URL}${onStream ? "?stream=1" : ""}`;
  const body = {
    contents: [{ role: "user", parts: [{ text: prompt }] }],
    generationConfig: {
      temperature: AI_TEMPERATURE,
      maxOutputTokens: AI_MAX_TOKENS,
    },
  };

  try {
    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });

    if (!res.ok) {
      const errText = await res.text().catch(() => "");
      console.error("[Gemini]", res.status, errText);
      return null;
    }

    if (onStream) {
      return await streamGeminiSSE(res, onStream);
    } else {
      const data = await res.json();
      return data.candidates?.[0]?.content?.parts?.[0]?.text || null;
    }
  } catch (e) {
    console.error("[Gemini]", e);
    return null;
  }
}

async function streamGeminiSSE(response, onChunk) {
  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "",
    fullText = "";

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split("\n");
    buffer = lines.pop() || "";

    for (const line of lines) {
      if (line.startsWith("data: ")) {
        const json = line.slice(6).trim();
        if (json === "[DONE]" || !json) continue;
        try {
          const data = JSON.parse(json);
          const arr = Array.isArray(data) ? data : [data];
          for (const item of arr) {
            const text = item.candidates?.[0]?.content?.parts?.[0]?.text || "";
            if (text) {
              fullText += text;
              onChunk(fullText);
            }
          }
        } catch (_) {}
      }
    }
  }
  return fullText;
}

// ─── Streaming generation ───────────────────────────────────────────
async function streamApp(id, desc, onProgress) {
  const prompt = buildPrompt(desc);

  try {
    let fullText = "";

    const onChunk = (text) => {
      fullText = text;
      if (onProgress) onProgress(text);
    };

    const result = await callAI(prompt, onChunk);
    if (!result) return null;

    let finalCode = result.replace(/<thinking>[\s\S]*?<\/thinking>\s*/g, "");
    finalCode = finalCode.replace(/^\s*```[\w]*\n?|```\s*$/g, "").trim();

    return finalCode;
  } catch (e) {
    console.log("[AI] Streaming:", e.message);
    return null;
  }
}

async function genWithAI(desc) {
  try {
    return await callAI(buildPrompt(desc), null);
  } catch (e) {
    console.log("[AI] Generation:", e.message);
    return null;
  }
}

// ═══════════════════════════════════════════════════════════════════════
// OS API (exposed to generated apps)
// ═══════════════════════════════════════════════════════════════════════

window.os = {
  window: {
    _id: null,
    get title() {
      const w = getWin(this._id);
      return w ? w.title : "";
    },
    set title(v) {
      const w = getWin(this._id);
      if (w) {
        w.title = v;
        updTitle(this._id);
      }
    },
    get icon() {
      const w = getWin(this._id);
      return w ? w.icon : "";
    },
    set icon(v) {
      const w = getWin(this._id);
      if (w) {
        w.icon = v;
        updTitle(this._id);
      }
    },
    get size() {
      const w = getWin(this._id);
      return w ? { w: w.w, h: w.h } : { w: 400, h: 300 };
    },
    resize(w, h) {
      resizeWin(this._id, w, h);
    },
  },
  fs: {
    read(k) {
      try {
        return localStorage.getItem("io_" + k);
      } catch (e) {
        return null;
      }
    },
    write(k, v) {
      try {
        localStorage.setItem("io_" + k, String(v));
        return true;
      } catch (e) {
        return false;
      }
    },
    list() {
      const a = [];
      for (let i = 0; i < localStorage.length; i++) {
        const k = localStorage.key(i);
        if (k && k.startsWith("io_"))
          a.push({ key: k.slice(3), size: localStorage.getItem(k).length });
      }
      return a;
    },
    delete(k) {
      try {
        localStorage.removeItem("io_" + k);
        return true;
      } catch (e) {
        return false;
      }
    },
  },
  notify(t, m) {
    showNotif(t, m);
  },
  get theme() {
    return "dark";
  },
  randomColor() {
    const c = [
      "#7c3aed",
      "#ef4444",
      "#f59e0b",
      "#10b981",
      "#3b82f6",
      "#ec4899",
      "#8b5cf6",
      "#14b8a6",
      "#f97316",
      "#06b6d4",
    ];
    return c[Math.floor(Math.random() * c.length)];
  },
  openApp(d) {
    openApp(d);
  },
};

// ═══════════════════════════════════════════════════════════════════════
// WINDOW MANAGER
// ═══════════════════════════════════════════════════════════════════════

function createWin(id, title, icon, w, h, x, y) {
  if (S.windows[id]) {
    focusWin(id);
    return S.windows[id];
  }
  const win = {
    id,
    title: title || "App",
    icon: icon || "📱",
    w: w || 520,
    h: h || 380,
    x: x || 80 + Math.random() * 120,
    y: y || 60 + Math.random() * 80,
    z: S.z++,
    max: false,
    min: false,
    prev: null,
  };
  S.windows[id] = win;
  S.order.push(id);
  renderWin(id);
  updTB();
  focusWin(id);
  return win;
}

function renderWin(id) {
  const w = S.windows[id];
  if (!w) return;
  const old = document.getElementById("w-" + id);
  if (old) old.remove();
  const el = document.createElement("div");
  el.className = "window" + (w.max ? " max" : "");
  el.id = "w-" + id;
  Object.assign(el.style, {
    left: w.x + "px",
    top: w.y + "px",
    width: w.w + "px",
    height: w.h + "px",
    zIndex: w.z,
  });
  el.dataset.id = id;
  el.innerHTML = `<div class="window-titlebar" onmousedown="dr(event,'${id}')"><div class="wc"><button class="wcc" onclick="cW('${id}')"></button><button class="wcm" onclick="mW('${id}')"></button><button class="wcx" onclick="MW('${id}')"></button></div><div class="t" id="wt-${id}"><span class="ie">${w.icon}</span>${w.title}</div><div class="wc" style="visibility:hidden"><button></button><button></button><button></button></div></div><div class="window-body" id="wb-${id}"></div><div class="wrz" onmousedown="rz(event,'${id}')"></div>`;
  document.getElementById("windows-container").appendChild(el);
  if (w.min) el.style.display = "none";
}

function getWin(id) {
  return S.windows[id] || null;
}
function updTitle(id) {
  const w = S.windows[id];
  if (!w) return;
  const e = document.getElementById("wt-" + id);
  if (e) e.innerHTML = `<span class="ie">${w.icon}</span>${w.title}`;
  updTB();
}

function focusWin(id) {
  const w = S.windows[id];
  if (!w) return;
  w.z = S.z++;
  const e = document.getElementById("w-" + id);
  if (e) e.style.zIndex = w.z;
  const i = S.order.indexOf(id);
  if (i > -1) S.order.splice(i, 1);
  S.order.push(id);
  updTB();
}

function cW(id) {
  const w = S.windows[id];
  if (!w) return;
  const e = document.getElementById("w-" + id);
  if (e) e.remove();
  delete S.windows[id];
  const i = S.order.indexOf(id);
  if (i > -1) S.order.splice(i, 1);
  updTB();
  if (S.order.length) focusWin(S.order[S.order.length - 1]);
}

function mW(id) {
  const w = S.windows[id];
  if (!w) return;
  w.min = !w.min;
  const e = document.getElementById("w-" + id);
  if (e) {
    e.style.display = w.min ? "none" : "";
    if (!w.min) focusWin(id);
  }
  updTB();
}

function MW(id) {
  const w = S.windows[id];
  if (!w) return;
  if (w.max) {
    w.max = false;
    if (w.prev) {
      w.x = w.prev.x;
      w.y = w.prev.y;
      w.w = w.prev.w;
      w.h = w.prev.h;
    }
  } else {
    w.prev = { x: w.x, y: w.y, w: w.w, h: w.h };
    w.max = true;
  }
  const el = document.getElementById("w-" + id);
  if (el) {
    el.classList.toggle("max", w.max);
    if (!w.max) {
      el.style.left = w.x + "px";
      el.style.top = w.y + "px";
      el.style.width = w.w + "px";
      el.style.height = w.h + "px";
    }
  }
  updTB();
}

function resizeWin(id, w, h) {
  const win = S.windows[id];
  if (!win || win.max) return;
  win.w = Math.max(300, w);
  win.h = Math.max(200, h);
  const e = document.getElementById("w-" + id);
  if (e) {
    e.style.width = win.w + "px";
    e.style.height = win.h + "px";
  }
}

function dr(e, id) {
  if (e.target.closest(".wc")) return;
  const w = S.windows[id];
  if (!w || w.max) return;
  focusWin(id);
  const sx = e.clientX,
    sy = e.clientY,
    sl = w.x,
    st = w.y;
  const mv = (ev) => {
    w.x = sl + (ev.clientX - sx);
    w.y = st + (ev.clientY - sy);
    const el = document.getElementById("w-" + id);
    if (el) {
      el.style.left = w.x + "px";
      el.style.top = w.y + "px";
    }
  };
  const up = () => {
    document.removeEventListener("mousemove", mv);
    document.removeEventListener("mouseup", up);
    window.removeEventListener("blur", up);
  };
  document.addEventListener("mousemove", mv);
  document.addEventListener("mouseup", up);
  window.addEventListener("blur", up);
}

function rz(e, id) {
  e.stopPropagation();
  const w = S.windows[id];
  if (!w || w.max) return;
  focusWin(id);
  const sx = e.clientX,
    sy = e.clientY,
    sw = w.w,
    sh = w.h;
  const mv = (ev) => {
    w.w = Math.max(300, sw + (ev.clientX - sx));
    w.h = Math.max(200, sh + (ev.clientY - sy));
    const el = document.getElementById("w-" + id);
    if (el) {
      el.style.width = w.w + "px";
      el.style.height = w.h + "px";
    }
  };
  const up = () => {
    document.removeEventListener("mousemove", mv);
    document.removeEventListener("mouseup", up);
    window.removeEventListener("blur", up);
  };
  document.addEventListener("mousemove", mv);
  document.addEventListener("mouseup", up);
  window.addEventListener("blur", up);
}

// ═══════════════════════════════════════════════════════════════════════
// APP LAUNCHER
// ═══════════════════════════════════════════════════════════════════════

function appDocument(id, html) {
  const appId = JSON.stringify(id);
  return `<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<style>
:root{--bg:#0f0f1a;--bg2:#1a1a2e;--bg3:#252540;--surface:#ffffff08;--surface-hover:#ffffff14;--border:#ffffff14;--accent:#7c3aed;--accent-hover:#6d28d9;--text:#e8e8f0;--text2:#9898b0}
*,*::before,*::after{box-sizing:border-box}
html,body{margin:0;width:100%;height:100%;background:transparent;color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",system-ui,sans-serif;color-scheme:dark}
body{overflow:auto}button,input,textarea,select{font:inherit}
</style>
<script>
(() => {
  const appId = ${appId};
  const parentOs = parent.os;
  const withWindow = (fn) => { const previous = parentOs.window._id; parentOs.window._id = appId; try { return fn(); } finally { parentOs.window._id = previous; } };
  window.os = {
    fs: parentOs.fs, notify: (...args) => parentOs.notify(...args),
    get theme() { return parentOs.theme; }, randomColor: () => parentOs.randomColor(),
    openApp: (desc) => parentOs.openApp(desc),
    window: { _id: appId, get title() { return withWindow(() => parentOs.window.title); }, set title(v) { withWindow(() => { parentOs.window.title = v; }); }, get icon() { return withWindow(() => parentOs.window.icon); }, set icon(v) { withWindow(() => { parentOs.window.icon = v; }); }, get size() { return withWindow(() => parentOs.window.size); }, resize: (w, h) => withWindow(() => parentOs.window.resize(w, h)) },
  };
})();
</script>
</head>
<body>${html}</body>
</html>`;
}

function iconFor(n) {
  const l = n.toLowerCase();
  if (l.includes("calc") || l.includes("math")) return "🧮";
  if (l.includes("todo") || l.includes("task") || l.includes("list"))
    return "✅";
  if (l.includes("note") || l.includes("memo")) return "📝";
  if (l.includes("paint") || l.includes("draw") || l.includes("sketch"))
    return "🎨";
  if (l.includes("clock") || l.includes("time") || l.includes("watch"))
    return "🕐";
  if (l.includes("timer") || l.includes("stopwatch")) return "⏱️";
  if (l.includes("weather")) return "🌤️";
  if (l.includes("chat") || l.includes("ai") || l.includes("assistant"))
    return "💬";
  if (l.includes("radio") || l.includes("garden")) return "📻";
  if (l.includes("music") || l.includes("player") || l.includes("sound"))
    return "🎵";
  if (l.includes("convert") || l.includes("unit")) return "📏";
  if (l.includes("tic") || l.includes("tac") || l.includes("toe")) return "❌";
  if (l.includes("color") || l.includes("picker")) return "🎨";
  return "📱";
}

function renderApp(id, desc, html) {
  const win = S.windows[id];
  if (!win) createWin(id, desc, iconFor(desc), 540, 400);
  const w = S.windows[id];
  if (!w) return;
  w.title = desc
    .split(" ")
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(" ");
  w.icon = iconFor(desc);
  updTitle(id);

  const b = document.getElementById("wb-" + id);
  if (!b) return;
  b.removeAttribute("style");
  b.innerHTML = "";
  if (html) {
    const frame = document.createElement("iframe");
    frame.className = "app-frame";
    frame.title = desc;
    frame.srcdoc = appDocument(id, html);
    b.appendChild(frame);
  }
  addDI(id, w.title, w.icon);
  updTB();
}

async function openApp(desc) {
  closeLauncher();
  const d = desc.trim();
  if (!d) return;
  const id =
    d
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_|_$/g, "") || "app";
  if (S.windows[id]) {
    focusWin(id);
    return;
  }
  if (appCache[id]) {
    renderApp(id, d, appCache[id]);
    return;
  }

  createWin(id, "Generating...", "⏳", 540, 400);
  const body = document.getElementById("wb-" + id);
  if (body) {
    body.style.overflow = "auto";
    body.style.background = "#0f0f1a";
    body.style.display = "flex";
    body.style.alignItems = "center";
    body.style.justifyContent = "center";
    body.innerHTML = `<div style="display:flex;flex-direction:column;align-items:center;justify-content:center;height:100%;padding:24px;text-align:center;gap:14px">
  <div style="width:44px;height:44px;border:3px solid rgba(124,58,237,0.15);border-top-color:#7c3aed;border-right-color:#a78bfa;border-radius:50%;animation:buildSpin 0.8s cubic-bezier(0.4,0,0.2,1) infinite"></div>
  <div style="font-size:16px;font-weight:500;color:#e8e8f0">${htmlEscape(d)}</div>
  <div id="build-st-${id}" style="font-size:12px;color:#9898b0;min-height:18px">Generating...</div>
  <div id="build-pv-${id}" style="width:100%;max-width:480px;max-height:180px;overflow:auto;background:rgba(0,0,0,0.3);border-radius:8px;padding:12px;font-family:monospace;font-size:11px;line-height:1.5;text-align:left;white-space:pre-wrap;word-break:break-all;color:#707090;display:none"></div>
</div>`;
  }

  const raw =
    (await streamApp(id, d, (txt) => {
      const el = document.getElementById("build-pv-" + id);
      const st = document.getElementById("build-st-" + id);
      if (!el || !st) return;
      el.style.display = "block";
      let clean = txt
        .replace(/<thinking>[\s\S]*?<\/thinking>/g, "")
        .replace(/```[\w]*\n?/g, "");
      el.textContent = clean.length > 1200 ? "…\n" + clean.slice(-1200) : clean;
      el.scrollTop = el.scrollHeight;
      st.textContent = "Generating...";
    })) || (await genWithAI(d));
  const cleaned = raw
    ? raw
        .replace(/^\s*```[\w]*\n?|```\s*$/g, "")
        .replace(/<thinking>[\s\S]*?<\/thinking>\n*/g, "")
    : null;
  const html = cleaned ? extractHTML(cleaned) : null;

  if (html) {
    appCache[id] = html;
    renderApp(id, d, html);
  } else {
    renderApp(id, d, generationErrorHTML(d));
  }
  updTB();
}

function addDI(id, name, emoji) {
  if (document.getElementById("di-" + id)) return;
  const el = document.createElement("div");
  el.className = "desktop-icon";
  el.id = "di-" + id;
  el.ondblclick = () => openApp(name);
  el.innerHTML = `<div class="icon-emoji">${emoji || "📱"}</div><div class="icon-label">${name}</div>`;
  document.getElementById("desktop-icons").appendChild(el);
}

// ═══════════════════════════════════════════════════════════════════════
// LAUNCHER
// ═══════════════════════════════════════════════════════════════════════

function toggleLauncher() {
  S.launcher ? closeLauncher() : openLauncher();
}

function openLauncher() {
  S.launcher = true;
  document.getElementById("launcher").classList.remove("hide");
  setTimeout(() => document.getElementById("launcher-inp").focus(), 50);
  document.getElementById("launcher-st").textContent = "";
  document.getElementById("launcher-sug").innerHTML = "";
}

function closeLauncher() {
  S.launcher = false;
  document.getElementById("launcher").classList.add("hide");
}
function onLauncherKey(e) {
  if (e.key === "Enter") searchApp();
  else if (e.key === "Escape") closeLauncher();
}

async function searchApp() {
  const inp = document.getElementById("launcher-inp");
  const q = inp.value.trim();
  if (!q) return;
  document.getElementById("launcher-go").disabled = true;
  inp.disabled = true;
  document.getElementById("launcher-st").textContent = "✦ Generating...";
  await openApp(q);
  setTimeout(() => {
    inp.value = "";
    inp.disabled = false;
    document.getElementById("launcher-go").disabled = false;
    document.getElementById("launcher-st").textContent = "";
  }, 500);
}

// ═══════════════════════════════════════════════════════════════════════
// TASKBAR
// ═══════════════════════════════════════════════════════════════════════

function updTB() {
  const c = document.getElementById("tb-apps");
  c.innerHTML = "";
  S.order.forEach((id) => {
    const w = S.windows[id];
    if (!w) return;
    const btn = document.createElement("button");
    btn.className =
      "tb-app" + (id === S.order[S.order.length - 1] ? " on" : "");
    btn.innerHTML = `${w.icon} ${w.title}`;
    btn.onclick = () => {
      if (w.min) {
        w.min = false;
        const el = document.getElementById("w-" + id);
        if (el) el.style.display = "";
        focusWin(id);
      } else if (id === S.order[S.order.length - 1]) mW(id);
      else focusWin(id);
    };
    c.appendChild(btn);
  });
}

// ═══════════════════════════════════════════════════════════════════════
// NOTIFICATIONS
// ═══════════════════════════════════════════════════════════════════════

function showNotif(t, m) {
  const c = document.getElementById("notif-box");
  const el = document.createElement("div");
  el.className = "notif";
  el.onclick = () => el.remove();
  el.innerHTML = `<div class="nf-t">${t}</div><div class="nf-m">${m}</div>`;
  c.appendChild(el);
  setTimeout(() => {
    if (el.parentElement) el.remove();
  }, 5000);
}

// ═══════════════════════════════════════════════════════════════════════
// CLOCK / EVENTS / WELCOME / BOOT
// ═══════════════════════════════════════════════════════════════════════

function clock() {
  document.getElementById("tb-clock").textContent =
    new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
}

document.addEventListener("contextmenu", (e) => {
  e.preventDefault();
  const m = document.getElementById("ctx");
  m.style.left = Math.min(e.clientX, window.innerWidth - 200) + "px";
  m.style.top = Math.min(e.clientY, window.innerHeight - 250) + "px";
  m.classList.remove("hide");
});
document.addEventListener("click", (e) => {
  if (!e.target.closest("#ctx"))
    document.getElementById("ctx").classList.add("hide");
});
document
  .getElementById("desktop")
  .addEventListener("click", () =>
    document.getElementById("ctx").classList.add("hide"),
  );

let _welcomed = false;

function showWelcome() {
  const id = "_welcome";
  if (S.windows[id]) {
    focusWin(id);
    return;
  }
  createWin(id, "Welcome", "✦", 480, 420);
  const body = document.getElementById("wb-" + id);
  if (body) {
    body.style.overflow = "auto";
    body.innerHTML = `
<div style="display:flex;flex-direction:column;align-items:center;justify-content:center;padding:32px;text-align:center;height:100%">
  <div style="font-size:56px;margin-bottom:8px;color:var(--accent)">✦</div>
  <h1 style="font-size:26px;font-weight:600;margin-bottom:4px">Welcome to Infinite OS</h1>
  <p style="font-size:13px;color:var(--text2);margin-bottom:20px;line-height:1.6">
    A web-based operating system where every app is generated
    <br>by AI on demand — powered by Google Gemini.
  </p>
  <div style="display:flex;flex-direction:column;gap:10px;width:100%;max-width:360px">
    <div style="display:flex;gap:12px;align-items:flex-start;background:var(--surface);padding:12px 16px;border-radius:var(--radius-sm);text-align:left">
      <span style="font-size:20px;flex-shrink:0">🔍</span>
      <div><strong style="font-size:13px">Launch anything</strong><br><span style="font-size:12px;color:var(--text2)">Click the ✦ button or press <kbd style="background:var(--bg3);padding:2px 6px;border-radius:4px;font-size:11px">Ctrl+K</kbd> to open the launcher. Describe any app and AI builds it instantly.</span></div>
    </div>
    <div style="display:flex;gap:12px;align-items:flex-start;background:var(--surface);padding:12px 16px;border-radius:var(--radius-sm);text-align:left">
      <span style="font-size:20px;flex-shrink:0">📦</span>
      <div><strong style="font-size:13px">Built-in apps</strong><br><span style="font-size:12px;color:var(--text2)">Right-click the desktop for quick access to Calculator, To-Do List, Notes, and Paint.</span></div>
    </div>
    <div style="display:flex;gap:12px;align-items:flex-start;background:var(--surface);padding:12px 16px;border-radius:var(--radius-sm);text-align:left">
      <span style="font-size:20px;flex-shrink:0">☁️</span>
      <div><strong style="font-size:13px">Cloud-powered AI</strong><br><span style="font-size:12px;color:var(--text2)">Apps are generated by Google Gemini via the cloud API backend.</span></div>
    </div>
  </div>
  <button onclick="cW('${id}')" style="margin-top:20px;padding:10px 32px;border:none;border-radius:var(--radius-sm);background:var(--accent);color:#fff;font-size:14px;cursor:pointer">Get Started</button>
</div>`;
  }
}

function showAbout() {
  document.getElementById("ctx").classList.add("hide");
  const o = document.createElement("div");
  o.className = "ab-o";
  o.onclick = (e) => {
    if (e.target === o) o.remove();
  };
  o.innerHTML = `<div class="ab-b"><h1>✦</h1><h2>Infinite OS</h2><p>A web operating system where every app is generated by AI on demand.</p><p style="font-size:12px;opacity:.4">AI: Google Gemini (cloud)<br>v1.1.0</p><button onclick="this.closest('.ab-o').remove()">Close</button></div>`;
  document.body.appendChild(o);
}

document.addEventListener("keydown", (e) => {
  if (e.key === "Escape" && S.launcher) closeLauncher();
  if ((e.ctrlKey || e.metaKey) && e.key === "k") {
    e.preventDefault();
    toggleLauncher();
  }
});

// ═══════════════════════════════════════════════════════════════════════
// BOOT SEQUENCE
// ═══════════════════════════════════════════════════════════════════════

function dismissBoot() {
  const b = document.getElementById("boot");
  b.classList.add("hide");
  setTimeout(() => {
    if (b) b.style.display = "none";
  }, 700);
}

createStars();
playStartupSound();
clock();
setInterval(clock, 1000);
console.log("✦ Infinite OS loaded");

// Boot sequence — phased loading with progress
const bootPhases = [
  { msg: "Loading kernel modules...", pct: 15, delay: 600 },
  { msg: "Starting AI engine...", pct: 35, delay: 1200 },
  { msg: "Connecting to Gemini...", pct: 60, delay: 1800 },
  { msg: "Preparing desktop...", pct: 85, delay: 2400 },
  { msg: "Backend AI ready", pct: 100, delay: 3000 },
];

bootPhases.forEach(({ msg, pct, delay }) => {
  setTimeout(() => bootMsg(msg, pct), delay);
});

setTimeout(() => {
  dismissBoot();
  if (!_welcomed) {
    _welcomed = true;
    setTimeout(showWelcome, 300);
  }
  updTB();
}, 3500);
